version: '3'

services:
  db:
    image: postgres
    restart: always
    volumes:
     - ~/opt/local/remaster_volume:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=${DDBNAME}
      - POSTGRES_USER=${DDBUSER}
      - POSTGRES_PASSWORD=${DDBPASSWORD}

  web:
    build:
      context: ./
      dockerfile: Dockerfile
    ports:
      - '8000:8000'
    env_file:
      - ./.env
    depends_on:
      - db
