version: '3.8'

services:
  db:
    image: mysql:5.6.51
    restart: always
    volumes:
     - ~/opt/local/remaster_volume:/var/lib/postgresql/
    environment:
     - .venv

  web:
    build:
      context: ./
      dockerfile: Dockerfile
    ports:
      - '8000:8000'
    depends_on:
      - db
